spring:
  application:
    name: server-provider
  jta:
    transaction-manager-id: prov-1
    log-dir: D:\logTest\1
server:
  port: 7777

eureka:
  client:
    healthcheck:
      enabled: true  #开启健康检查
    service-url:
      defaultZone: http://localhost:9999/eureka
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}|${random.value}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 30 # 续约到期时间（默认90秒）
management:
  security:
    enabled: false
logging:
  level: debug
